apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pes2ug23cs057
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pes2ug23cs057-nginx:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
