apiVersion: v1
kind: Service
metadata:
  name: pes2ug23cs057-service
  namespace: pes2ug23cs057-beta
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80        # Service port
    targetPort: 80  # Container port
